FROM elixir:1.19.5

WORKDIR /app

RUN apt-get update && apt-get install -y \
  build-essential \
  git \
  inotify-tools \
  && rm -rf /var/lib/apt/lists/*

RUN mix local.hex --force && mix local.rebar --force

COPY mix.exs mix.lock ./

COPY . .

EXPOSE 4000

CMD ["sh", "-c", "mix deps.get && mix phx.server"]
